# Dockerfile.frontend
FROM nginx:stable-alpine

# Удаляем стандартный конфиг
RUN rm /etc/nginx/conf.d/default.conf

# Копируем свой конфиг
COPY nginx.conf /etc/nginx/conf.d/

# Копируем только папку frontend в папку html
COPY frontend/ /usr/share/nginx/html/

# ЗДЕСЬ УКАЖИТЕ ВАШ ПОРТ
EXPOSE 80
